### ISSUE TITLE
Create minimum speed for P control loop for arm

### ISSUE THREAD

**Issue by AlphaRant9** [Waterloo-Robotics/PowerPlay7247#1]
Realised I didn't do that, that could cause some issues with slowing down to an unmovable speed. Shouldn't take much, but it needs done.

**Comment by AlphaRant9** [comment]
I can perform this fix as soon as I get to the trailer or even when I get home, but if I do it at home it might require tuning.

**Comment by H2OLooBots** [comment]
Close this issue with the next commit, resolved with the exception of tuning.
