### ISSUE TITLE
Weird bugs with shoulder P control?

### ISSUE THREAD

**Issue by AlphaRant9** [Waterloo-Robotics/PowerPlay7247#2]
P controller is causing some weird things to happen, I'm going to need to look back at the control loop to see what I can do. Maybe nick can look into this as well.

**Comment by AlphaRant9** [comment]
@NicholasRHeinz, Patrick mentioned we needed to add I and D. Do we have a timetable for this?

**Comment by H2OLooBots** [comment]
We decided to just remove proportional control for the arm.
